### ISSUE TITLE
Automatic pricing for enchanted books not working

### ISSUE THREAD

**Issue by TheRonGDD** [alfalfascout/CustomVillageTrades#30]
Using this with the latest .10 beta causes no enchantment. I have trades 1 and 2 also and more below but omitted due to irrelevancy.

[11:01:06 WARN]: [CustomVillageTrades] This book has no enchantments.

worlds:
  world: config.yml
  world_nether: config.yml
  world_the_end: config.yml
all_villagers: none
currency: emerald
allow_vanilla_trades: false
overwrite_unknown_villagers: true
librarian:
    trade3:
      result:
        material: enchanted_book
        enchantment:
          allow_treasure: true
      ingredient1: auto

**Comment by alfalfascout** [comment]
Thank you for letting me know! I'll look into it and see if I can't figure out what went wrong.

**Comment by alfalfascout** [comment]
Try this release: [Beta 0.10.1](https://github.com/alfalfascout/CustomVillageTrades/releases/tag/v0.10.1-beta)
